name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          npm run build
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf .
          cp -r $GITHUB_WORKSPACE/* .
          rm -rf .git
          rm -rf .github
          rm -rf node_modules
          rm -f .gitignore .github/workflows/deploy.yml
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
